version: '3'

tasks:
  build:
    cmds:
      - go build -o ./build/audiolito ./cmd/*.go
      - GOOS=windows GOARCH=amd64 go build -o ./build/audiolito.exe ./cmd/*.go
    sources:
      - cmd/*.go
      - internal/**/*.go
    generates:
      - build/audiolito
      - build/audiolito.exe
